Repository kowainik/github-graphql, pull requests merged in 2020-12, with the labels that each got.

#9 [#3] Create initial GH API
  .github/workflows/ci.yml
  src/GitHub.hs
Labels: GraphQL AST, endpoint

#14 [#12] Convert GitHub AST types to GraphQL query type
  src/GitHub.hs
  src/GitHub/GraphQL.hs
Labels: GraphQL AST, render

#15 Update CI config
  .github/dependabot.yml
  .github/workflows/ci.yml
Labels: CI

#16 [#5] Render GraphQL AST pretty
  github-graphql.cabal
  src/GitHub/GraphQL.hs
  src/GitHub/Render.hs
  test/Spec.hs
  test/Test/Render.hs
Labels: GraphQL AST, render

#17 [#13] Implement endpoint that will take Query and call the real API
  github-graphql.cabal
  src/GitHub/Query.hs
Labels: endpoint
